// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aynilyxahjivimcgohvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bmlseXhhaGppdmltY2dvaHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkyNzIsImV4cCI6MjA2NTU5NTI3Mn0.zg1Svqs0uZQOjRBeAOkHiMfzjlbkpn8RyuHagFzw0rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);